"""Existing ML evaluation and screening results."""

import plotly.express as px
import streamlit as st

from src.ml import load_saved_ml_results
from src.visualizations import FEATURE_LABELS


def render(data, source_label: str) -> None:
    """Render saved project results without fitting models on page navigation."""

    st.title("ML evidence")
    st.caption("Evaluation results and candidate screening outputs generated by the existing notebook.")

    try:
        results = load_saved_ml_results()
    except (OSError, ValueError):
        st.warning("The saved project ML results could not be loaded.")
        return

    st.subheader("Model comparison")
    metric_columns = ["Model", "Accuracy", "Precision", "Recall", "F1 Score", "ROC-AUC"]
    model_metrics = results.model_comparison.loc[
        :, [column for column in metric_columns if column in results.model_comparison.columns]
    ].copy()
    st.dataframe(
        model_metrics.round(3),
        hide_index=True,
        width="stretch",
    )
    st.caption(
        "These are the repository's saved evaluation results; they are not retrained when this page opens."
    )

    chart_metrics = [column for column in ["Accuracy", "F1 Score", "ROC-AUC"] if column in model_metrics]
    chart_data = model_metrics.melt(
        id_vars="Model",
        value_vars=chart_metrics,
        var_name="Metric",
        value_name="Score",
    )
    comparison_chart = px.bar(
        chart_data,
        x="Score",
        y="Metric",
        color="Model",
        barmode="group",
        orientation="h",
        range_x=[0, 1],
        labels={"Score": "Saved score", "Metric": ""},
        title="Selected saved metrics",
        color_discrete_sequence=["#d95757", "#aab2bd"],
    )
    comparison_chart.update_layout(
        height=320,
        margin=dict(l=10, r=10, t=55, b=10),
        legend_title_text="",
    )
    st.plotly_chart(comparison_chart, use_container_width=True, config={"displayModeBar": False})

    st.subheader("Random Forest feature importance")
    importance = results.feature_importance.copy()
    importance["Feature"] = importance["Feature"].map(FEATURE_LABELS).fillna(importance["Feature"])
    importance = importance.sort_values("Importance", ascending=False).head(8)
    importance_chart = px.bar(
        importance.sort_values("Importance"),
        x="Importance",
        y="Feature",
        orientation="h",
        labels={"Importance": "Saved importance", "Feature": ""},
        title="Top saved features",
        color_discrete_sequence=["#d95757"],
    )
    importance_chart.update_layout(
        height=360,
        margin=dict(l=10, r=10, t=55, b=10),
        showlegend=False,
    )
    st.plotly_chart(importance_chart, use_container_width=True, config={"displayModeBar": False})
    st.caption("Shown: the eight largest values from the project's saved Random Forest importance output.")

    st.subheader("Screening scope")
    st.write(
        "The notebook trained Logistic Regression and Random Forest to separate "
        "CONFIRMED from FALSE POSITIVE objects. CANDIDATE is kept as the catalog label "
        "and was screened by the saved Random Forest confirmed-probability output."
    )
    screening = results.candidate_predictions.copy()
    priority_counts = screening["priority"].value_counts().reindex(
        ["High", "Medium", "Low"], fill_value=0
    )
    priority_columns = st.columns(3)
    for column, priority in zip(priority_columns, ["High", "Medium", "Low"]):
        column.metric(f"{priority} priority", f"{int(priority_counts[priority]):,}")

    top_screening = screening.sort_values(
        "predicted_confirmed_probability", ascending=False
    ).head(8)
    top_screening = top_screening.loc[
        :, ["kepoi_name", "kepid", "predicted_confirmed_probability", "priority", "outlier_flag"]
    ].rename(
        columns={
            "kepoi_name": "KOI identifier",
            "kepid": "Kepler ID",
            "predicted_confirmed_probability": "Screening score",
            "priority": "Priority",
            "outlier_flag": "Outlier flag",
        }
    )
    top_screening["Screening score"] = top_screening["Screening score"].map(lambda value: f"{value:.1%}")
    top_screening["Outlier flag"] = top_screening["Outlier flag"].map(
        lambda value: "Flagged" if int(value) == 1 else "No"
    )
    st.dataframe(top_screening, hide_index=True, width="stretch")
    st.caption("Top saved candidate screening rows, ordered by the existing screening score.")
    st.caption("Screening priority is for further review and is not scientific confirmation.")
    st.caption(f"Saved candidate screening rows: {len(screening):,}")
    st.caption(f"Source: `{source_label}`")
