"""Useful graphs generated by the existing project analysis."""

from pathlib import Path

import pandas as pd
import streamlit as st

from app.modeling import get_model_bundle


PROJECT_ROOT = Path(__file__).resolve().parents[2]
FIGURES = PROJECT_ROOT / "results" / "figures"


def _show_figure(filename: str, caption: str) -> None:
    path = FIGURES / filename
    if path.exists():
        st.image(str(path), use_container_width=True)
        st.caption(caption)
    else:
        st.warning(f"The generated graph is missing: {filename}")


def render(data: pd.DataFrame, source_label: str) -> None:
    """Render a curated set of existing figures with a reason for each."""

    st.title("Visualizations")
    st.caption("Existing analysis graphs, grouped so each view answers a specific question.")

    catalog_tab, relationships_tab, evidence_tab = st.tabs(
        ["Catalog overview", "Measurements", "Evidence & models"]
    )

    with catalog_tab:
        st.subheader("How is the catalog classified?")
        _show_figure(
            "01_classification_distribution.png",
            "Helps understand how many records have each catalog classification.",
        )
        _show_figure(
            "02_radius_by_classification.png",
            "Helps compare recorded planetary-radius distributions between classifications.",
        )
        _show_figure(
            "03_period_by_classification.png",
            "Helps compare the recorded orbital-period distributions between classifications.",
        )

    with relationships_tab:
        st.subheader("How do the recorded measurements relate?")
        _show_figure(
            "04_radius_vs_transit_depth.png",
            "Helps inspect whether radius and transit depth move together in the catalog records.",
        )
        _show_figure(
            "05_period_vs_temperature.png",
            "Helps inspect the relationship between orbital period and equilibrium temperature.",
        )
        _show_figure(
            "06_period_vs_transit_duration.png",
            "Helps inspect how orbital period and transit duration are distributed together.",
        )
        _show_figure(
            "07_star_vs_planet_temperature.png",
            "Helps compare host-star effective temperature with recorded equilibrium temperature.",
        )

    with evidence_tab:
        st.subheader("What does the existing analysis use as evidence?")
        _show_figure(
            "08_correlation_heatmap.png",
            "Helps inspect correlations among the numeric variables included in the existing analysis.",
        )
        try:
            bundle = get_model_bundle(data)
        except Exception as exc:
            st.warning(f"Model-derived charts are unavailable: {exc}")
        else:
            st.markdown("**Random Forest feature importance**")
            st.caption("Shows the relative importance values from the existing fitted Random Forest workflow.")
            importance = bundle["feature_importance"].copy().head(10).sort_values("importance")
            st.bar_chart(importance.set_index("feature")["importance"], horizontal=True)

            st.markdown("**Model comparison**")
            st.caption("Compares only the accuracy, precision, recall, and F1 values calculated by the project.")
            st.bar_chart(bundle["metrics"].round(3))

    st.caption(f"Graphs are loaded from `results/figures`; catalog source: `{source_label}`.")
