"""Reusable access to the project's existing classification work."""

from __future__ import annotations

import math
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler


PROJECT_ROOT = Path(__file__).resolve().parents[1]
TRAIN_PATH = PROJECT_ROOT / "reports" / "kepler_train_by_host.xls"
MODEL_COMPARISON_PATH = PROJECT_ROOT / "member 2" / "member2_model_comparison.csv"
FEATURE_IMPORTANCE_PATH = PROJECT_ROOT / "member 2" / "member2_feature_importance.csv"
CANDIDATE_PREDICTIONS_PATH = PROJECT_ROOT / "member 2" / "memeber2_candidate_predictions.csv"

# This is the feature list used by notebooks/member2_classification.ipynb.
FEATURE_COLUMNS = (
    "koi_period",
    "koi_duration",
    "koi_prad",
    "koi_teq",
    "koi_insol",
    "koi_model_snr",
    "koi_steff",
    "koi_slogg",
    "koi_srad",
    "koi_kepmag",
)
MODEL_NAMES = ("Random Forest", "Logistic Regression")
CLASS_LABELS = {0: "FALSE POSITIVE", 1: "CONFIRMED"}


@dataclass(frozen=True)
class ModelPrediction:
    """A binary screening result for one catalog row."""

    available: bool
    model_name: str
    predicted_class: str | None
    probabilities: dict[str, float]
    source: str | None = None


@dataclass(frozen=True)
class ModelBundle:
    """Cached models and saved results produced by the project notebook."""

    models: dict[str, Any]
    model_comparison: pd.DataFrame
    candidate_predictions: pd.DataFrame


@dataclass(frozen=True)
class SavedMLResults:
    """Saved evaluation and candidate-screening outputs from the project."""

    model_comparison: pd.DataFrame
    feature_importance: pd.DataFrame
    candidate_predictions: pd.DataFrame


def _build_models() -> dict[str, Any]:
    """Build the same two estimators used by the existing notebook."""

    return {
        "Logistic Regression": Pipeline(
            [
                ("scaler", StandardScaler()),
                ("model", LogisticRegression(max_iter=1000, random_state=42)),
            ]
        ),
        "Random Forest": RandomForestClassifier(
            n_estimators=300,
            random_state=42,
            n_jobs=-1,
        ),
    }


@lru_cache(maxsize=1)
def load_saved_ml_results() -> SavedMLResults:
    """Load the CSV artifacts generated by the existing classification notebook."""

    return SavedMLResults(
        model_comparison=pd.read_csv(MODEL_COMPARISON_PATH),
        feature_importance=pd.read_csv(FEATURE_IMPORTANCE_PATH),
        candidate_predictions=pd.read_csv(CANDIDATE_PREDICTIONS_PATH, low_memory=False),
    )


@lru_cache(maxsize=1)
def load_ml_bundle() -> ModelBundle:
    """Load saved results and fit the notebook-equivalent models once per process.

    The repository does not contain serialized model files. The train split is
    already prepared by host in ``reports/kepler_train_by_host.xls``; fitting
    from that file preserves the notebook's data preparation and model setup.
    ``lru_cache`` prevents model fitting on every Streamlit rerun.
    """

    train_data = pd.read_csv(TRAIN_PATH, low_memory=False)
    train_labeled = train_data[
        train_data["koi_disposition"].isin(["CONFIRMED", "FALSE POSITIVE"])
    ].copy()
    train_labeled["target"] = (train_labeled["koi_disposition"] == "CONFIRMED").astype(int)

    train_features = train_labeled.loc[:, FEATURE_COLUMNS]
    train_labels = train_labeled["target"]
    models = _build_models()
    for model in models.values():
        model.fit(train_features, train_labels)

    saved_results = load_saved_ml_results()
    return ModelBundle(
        models=models,
        model_comparison=saved_results.model_comparison,
        candidate_predictions=saved_results.candidate_predictions,
    )


def _saved_candidate_probability(row: pd.Series, bundle: ModelBundle) -> float | None:
    """Return the saved Random Forest probability when this row is in the artifact."""

    if "rowid" not in row or "rowid" not in bundle.candidate_predictions.columns:
        return None
    try:
        rowid = int(float(row["rowid"]))
    except (TypeError, ValueError):
        return None

    matches = bundle.candidate_predictions[
        bundle.candidate_predictions["rowid"] == rowid
    ]
    if matches.empty:
        return None
    probability = matches.iloc[0].get("predicted_confirmed_probability")
    try:
        probability = float(probability)
    except (TypeError, ValueError):
        return None
    if not math.isfinite(probability) or not 0 <= probability <= 1:
        return None
    return probability


def predict_selected(row: pd.Series, model_name: str = "Random Forest") -> ModelPrediction:
    """Predict the selected row with one of the project's cached models."""

    if model_name not in MODEL_NAMES:
        raise ValueError(f"Unknown model: {model_name}")

    try:
        bundle = load_ml_bundle()
        features = pd.DataFrame(
            [[row.get(column) for column in FEATURE_COLUMNS]],
            columns=FEATURE_COLUMNS,
        )
        if features.isna().any().any():
            return ModelPrediction(False, model_name, None, {})

        model = bundle.models[model_name]
        predicted_id = int(model.predict(features)[0])
        predicted_probabilities = model.predict_proba(features)[0]
        probabilities = {
            CLASS_LABELS[int(class_id)]: float(probability)
            for class_id, probability in zip(model.classes_, predicted_probabilities)
        }
        source = "Cached notebook-equivalent inference"

        # Prefer the saved candidate output for the Random Forest when it
        # contains this row. It is the project's generated candidate artifact.
        saved_probability = (
            _saved_candidate_probability(row, bundle)
            if model_name == "Random Forest"
            else None
        )
        if saved_probability is not None:
            probabilities = {
                "FALSE POSITIVE": 1.0 - saved_probability,
                "CONFIRMED": saved_probability,
            }
            source = "Saved candidate prediction artifact"

        predicted_class = max(probabilities, key=probabilities.get)
        return ModelPrediction(True, model_name, predicted_class, probabilities, source)
    except (OSError, KeyError, ValueError, TypeError):
        return ModelPrediction(False, model_name, None, {})
